version: "3.7"
services:
  # postgresql://postgres:postgres@localhost:5433/decimal-precision-repro?sslmode=disable
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: